In [117]:
import pandas as pd
import mlxtend
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
data = pd.read_excel('greenhouse-gas-emissions-by-region-industry-and-household-year-ended-2018.xlsx')
data.head()

,region,Industry,gas,units,magnitude,year,data_val
0,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2007,811.63
1,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2008,777.95
2,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2009,684.00
3,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2010,706.56
4,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2011,764.30

In [118]:
data['Industry'] = data['Industry'].str.strip()
data = data[~data['Industry'].str.contains('Total')]
data

,region,Industry,gas,units,magnitude,year,data_val
0,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2007,811.63
1,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2008,777.95
2,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2009,684.00
3,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2010,706.56
4,Auckland,Agriculture,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2011,764.30
...,...,...,...,...,...,...,...
1975,West Coast,Service industries,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2014,47.11
1976,West Coast,Service industries,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2015,45.02
1977,West Coast,Service industries,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2016,40.81
1978,West Coast,Service industries,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2017,41.89
1979,West Coast,Service industries,Carbon dioxide equivalents,Kilotonnes,Carbon dioxide equivalents,2018,44.58

In [119]:
basket = (data[data['gas'] == "Carbon dioxide equivalents"]
         .groupby(['Industry', 'region'])['data_val']
         .sum().unstack().reset_index().fillna(0)
         .set_index('Industry'))
basket

region,Auckland,Bay of Plenty,Canterbury,Gisborne,Hawke's Bay,Manawatu-Whanganui,Marlborough,Northland,Otago,Southland,Taranaki,Tasman/Nelson,Waikato,Wellington,West Coast
Industry,,,,,,,,,,,,,,,
Agriculture,9062.00,17486.68,85461.17,13408.23,28959.69,54669.16,5946.00,25797.32,43418.73,49383.09,26819.98,5931.46,87988.46,13982.18,8106.76
Construction,3654.30,577.91,1737.97,65.34,258.77,360.88,92.56,237.12,585.65,192.09,242.70,173.63,865.94,1016.44,79.82
"Electricity, gas, water, and waste services",24030.85,3818.97,6276.83,466.50,1593.51,1663.06,343.87,2117.65,2107.90,772.49,17869.88,805.45,46497.30,4593.94,317.06
"Forestry, fishing, and mining",815.06,1730.60,4047.76,704.36,770.16,786.38,740.71,996.19,1489.55,1560.80,11164.92,1519.01,5257.62,542.13,4546.46
Goods-producing industries,67989.50,8105.62,20414.42,799.40,3773.64,5453.90,993.46,24819.71,4702.64,12913.19,28811.37,2663.65,60752.76,8664.83,1708.67
Households,35827.74,6465.93,13457.43,1023.70,3411.88,5609.55,1147.28,4119.71,4828.85,2103.43,2663.48,2519.54,10705.64,11707.37,1052.78
Manufacturing,40304.35,3708.77,12399.62,267.57,1921.35,3429.93,557.03,22464.97,2009.03,11948.63,10698.79,1684.58,13389.51,3054.47,1311.77
Primary industries,9877.07,19217.29,89508.93,14112.62,29729.85,55455.55,6686.69,26793.49,44908.28,50943.90,37984.92,7450.48,93246.11,14524.30,12653.20
Service industries,22224.10,4414.55,9847.67,533.97,1899.60,2814.83,652.54,1653.43,3979.97,1846.75,1466.07,1549.61,4802.93,8272.42,561.11
"Services excluding transport, postal, and warehousing",13160.58,2500.93,4401.71,271.46,1061.02,1616.73,306.64,1012.28,1636.50,587.55,749.48,653.28,2907.62,4720.70,241.90
"Transport, postal, and warehousing",9063.51,1913.62,5445.97,262.51,838.58,1198.10,345.90,641.17,2343.46,1259.19,716.56,896.35,1895.32,3551.71,319.20

In [120]:
def encode_units(x):
    if x <= 10000:
        return 0
    if x >= 10000:
        return 1
basket_sets = basket.applymap(encode_units)
basket_sets

region,Auckland,Bay of Plenty,Canterbury,Gisborne,Hawke's Bay,Manawatu-Whanganui,Marlborough,Northland,Otago,Southland,Taranaki,Tasman/Nelson,Waikato,Wellington,West Coast
Industry,,,,,,,,,,,,,,,
Agriculture,0,1,1,1,1,1,0,1,1,1,1,0,1,1,0
Construction,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"Electricity, gas, water, and waste services",1,0,0,0,0,0,0,0,0,0,1,0,1,0,0
"Forestry, fishing, and mining",0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Goods-producing industries,1,0,1,0,0,0,0,1,0,1,1,0,1,0,0
Households,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0
Manufacturing,1,0,1,0,0,0,0,1,0,1,1,0,1,0,0
Primary industries,0,1,1,1,1,1,0,1,1,1,1,0,1,1,1
Service industries,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"Services excluding transport, postal, and warehousing",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"Transport, postal, and warehousing",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [121]:
frequent_itemsets = apriori(basket_sets, min_support = 0.054, use_colnames=True)
rules = association_rules(frequent_itemsets, metric = "lift", min_threshold = 1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Canterbury),(Auckland),0.454545,0.545455,0.272727,0.600000,1.100000,0.024793,1.136364
1,(Auckland),(Canterbury),0.545455,0.454545,0.272727,0.500000,1.100000,0.024793,1.090909
2,(Auckland),(Waikato),0.545455,0.545455,0.363636,0.666667,1.222222,0.066116,1.363636
3,(Waikato),(Auckland),0.545455,0.545455,0.363636,0.666667,1.222222,0.066116,1.363636
4,(Canterbury),(Bay of Plenty),0.454545,0.181818,0.181818,0.400000,2.200000,0.099174,1.363636